// Code generated by `wos -gen-go elements/metalens.json -gen-name metalens_native`; DO NOT EDIT.
//
// metalens_native — 超表面透镜（双曲相位）, graduated from the scripted element "metalens".
// phase (rad): -sign*(2*pi/wl0)*(sqrt(r*r+f*f) - f)
// amplitude: 1
package optics

import (
	"fmt"
	"math"
)

func init() {
	RegisterGeneratedElement("metalens_native", newGenMetalensNative, ElementDoc{
		Label: "超表面透镜（双曲相位）",
		Help:  "把设计波长 λ0 下的双曲相位掩模 φ(r) = -(2π/λ0)·(√(r²+f²) − f) 写进元件：在 λ0 处严格聚焦到 f，其它波长按衍射规律移到 f·λ0/λ（色散）。元件轮廓即通光孔径。",
		Params: []ParamSpec{
			{Key: "f", Label: "设计焦距 f", Unit: "m", Kind: "float", Min: 0.001, Max: 10, Step: 0.001, Default: 0.3, Help: "设计波长下的焦距"},
			{Key: "wl0", Label: "设计波长 λ0", Unit: "m", Kind: "float", Min: 1e-09, Max: 1e-05, Step: 1e-09, Default: 6.328e-07, Help: "元件的相位按这个波长写死；实际焦点 z = f·λ0/λ"},
			{Key: "sign", Label: "会聚/发散", Kind: "choice", Default: "1", Choices: []string{"1", "-1"}, Help: "1 = 会聚（正透镜），-1 = 发散（负透镜）"},
		},
		Class: "lens",
	}, BehaviorTransmit)
}

// genMetalensNativeEl implements "metalens_native" as native code.
type genMetalensNativeEl struct {
	p_f    float64
	p_wl0  float64
	p_sign float64
}

func newGenMetalensNative(p map[string]any) (Element, error) {
	el := &genMetalensNativeEl{}
	v_f, err := genParamNum(p, "f", 0.3)
	if err != nil {
		return nil, fmt.Errorf("metalens_native: %v", err)
	}
	el.p_f = v_f
	v_wl0, err := genParamNum(p, "wl0", 6.328e-07)
	if err != nil {
		return nil, fmt.Errorf("metalens_native: %v", err)
	}
	el.p_wl0 = v_wl0
	v_sign, err := genParamNum(p, "sign", 1)
	if err != nil {
		return nil, fmt.Errorf("metalens_native: %v", err)
	}
	el.p_sign = v_sign
	return el, nil
}

func (e *genMetalensNativeEl) Apply(f *Field, ctx *Context) error {
	n := f.N
	for j := 0; j < n; j++ {
		yv := f.Y(j)
		for i := 0; i < n; i++ {
			xv := f.X(i)
			rv := math.Hypot(xv, yv)
			idx := j*n + i
			t := cexpI(((-(e.p_sign) * ((2 * math.Pi) / e.p_wl0)) * (math.Sqrt(((rv * rv) + (e.p_f * e.p_f))) - e.p_f)))
			f.Ex[idx] *= t
			if f.Polarized && f.Ey != nil {
				f.Ey[idx] *= t
			}
		}
	}
	return nil
}
